import { Box, Container, Grid } from '@mui/material'
import Head from 'next/head'
import { DashboardLayout } from '../src/components/dashboard-layout'
import { Activity } from '../src/components/dashboard/activity'
import { Profile } from '../src/components/dashboard/profile'
import { Security } from '../src/components/dashboard/secutity'

const Dashboard = () => (
  <>
    <Head>
      <title>DashBoard</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <Box component="main" sx={{ flexGrow: 1, py: 8 }}>
      <Container maxWidth={false}>
        <Grid container spacing={3}>
          <Grid item lg={12} sm={12} xl={12} xs={12}>
            <Profile />
          </Grid>
          <Grid item lg={12} sm={12} xl={12} xs={12}>
            <Security />
          </Grid>
          <Grid item lg={12} sm={12} xl={12} xs={12}>
            <Activity />
          </Grid>
        </Grid>
      </Container>
    </Box>
  </>
)

Dashboard.getLayout = (page) => <DashboardLayout>{page}</DashboardLayout>

export default Dashboard
